import { YAML } from "bun";

const EMPTY_MAPPING_SPACE = /: \n/g;

/**
 * Pure projection shared by the legacy writer and strict adoption qualification.
 * Input and output contain private runtime values: never log or serialize them
 * into reports or public receipts. Target order and key order are preserved so
 * existing generated bytes can be checked exactly. This performs no I/O.
 */
export function renderManagedComposeEnvOverride(opts: {
  readonly targetServices: readonly string[];
  readonly globalEnv: Readonly<Record<string, string>>;
  readonly serviceEnv: Readonly<
    Record<string, Readonly<Record<string, string>>>
  >;
}): string | null {
  const services: Record<
    string,
    { readonly environment: Readonly<Record<string, string>> }
  > = {};
  for (const service of opts.targetServices) {
    const env = opts.serviceEnv[service] ?? opts.globalEnv;
    if (Object.keys(env).length > 0) {
      services[service] = { environment: env };
    }
  }
  if (Object.keys(services).length === 0) {
    return null;
  }
  const text = YAML.stringify({ services }, null, 2).replaceAll(
    EMPTY_MAPPING_SPACE,
    ":\n"
  );
  return text.endsWith("\n") ? text : `${text}\n`;
}
