import { homedir } from "node:os";
import { resolve } from "node:path";

import { GLOBAL_CADDY_DIR_NAME, GLOBAL_HACK_DIR_NAME } from "../constants.ts";
import { pathExists } from "./fs.ts";

export const HACK_HOST_TRUST_BUNDLE_FILENAME =
  "caddy-host-trust-bundle.pem" as const;
export const HACK_HOST_TRUST_ENV_FILENAME = "caddy-host-trust-env.sh" as const;

export function resolveHackLocalCaCertPath(input?: {
  readonly home?: string | null;
}): string {
  const home = input?.home?.trim() || process.env.HOME?.trim() || homedir();
  return resolve(
    home,
    GLOBAL_HACK_DIR_NAME,
    GLOBAL_CADDY_DIR_NAME,
    "pki",
    "caddy-local-authority.crt"
  );
}

export async function findHackLocalCaCertPath(input?: {
  readonly home?: string | null;
}): Promise<string | null> {
  const certPath = resolveHackLocalCaCertPath(input);
  return (await pathExists(certPath)) ? certPath : null;
}

export function resolveHackHostTrustBundlePath(input?: {
  readonly home?: string | null;
}): string {
  const home = input?.home?.trim() || process.env.HOME?.trim() || homedir();
  return resolve(
    home,
    GLOBAL_HACK_DIR_NAME,
    GLOBAL_CADDY_DIR_NAME,
    "pki",
    HACK_HOST_TRUST_BUNDLE_FILENAME
  );
}

export async function findHackHostTrustBundlePath(input?: {
  readonly home?: string | null;
}): Promise<string | null> {
  const bundlePath = resolveHackHostTrustBundlePath(input);
  return (await pathExists(bundlePath)) ? bundlePath : null;
}

export function resolveHackHostTrustEnvScriptPath(input?: {
  readonly home?: string | null;
}): string {
  const home = input?.home?.trim() || process.env.HOME?.trim() || homedir();
  return resolve(
    home,
    GLOBAL_HACK_DIR_NAME,
    GLOBAL_CADDY_DIR_NAME,
    "pki",
    HACK_HOST_TRUST_ENV_FILENAME
  );
}

export function buildHackHostTrustEnvironment(input: {
  readonly certPath: string;
  readonly bundlePath?: string | null;
}): Record<string, string> {
  const env: Record<string, string> = {
    NODE_EXTRA_CA_CERTS: input.certPath,
    HACK_LOCAL_CA_CERT: input.certPath,
  };

  const bundlePath = input.bundlePath?.trim();
  if (!bundlePath) {
    return env;
  }

  return {
    ...env,
    SSL_CERT_FILE: bundlePath,
    CURL_CA_BUNDLE: bundlePath,
    REQUESTS_CA_BUNDLE: bundlePath,
    GIT_SSL_CAINFO: bundlePath,
    HACK_HOST_TRUST_BUNDLE: bundlePath,
  };
}

export async function appendHackHostTrustEnvironment(
  env: Readonly<Record<string, string>>
): Promise<Record<string, string>> {
  const certPath = await findHackLocalCaCertPath();
  if (!certPath) {
    return { ...env };
  }

  const bundlePath = await findHackHostTrustBundlePath();
  return {
    ...env,
    ...buildHackHostTrustEnvironment({
      certPath,
      bundlePath,
    }),
  };
}

export function renderHackHostTrustShellExports(input: {
  readonly certPath: string;
  readonly bundlePath?: string | null;
}): string {
  const exports = buildHackHostTrustEnvironment(input);
  return [
    "#!/usr/bin/env sh",
    "# Auto-generated by `hack global trust`.",
    ...Object.entries(exports).map(
      ([key, value]) => `export ${key}=${shellQuote(value)}`
    ),
    "",
  ].join("\n");
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}
