//! Container-only persistence qualification, independent of VM shutdown/flush.
//!
//! Requires a virgin private candidate home with prepared provider/engine artifacts,
//! an explicitly hashed local Bun image archive, and an external 300-second watchdog.
//! Never select an application home: existing runtime/graph state is refused before
//! effects. Only the checked preparation lock may preexist. Failure retains this
//! fixture's volume and stops only its newly owned VM.
//! Set HACK_VOLUME_INTEGRITY_ROOT, HACK_VOLUME_INTEGRITY_IMAGE (sha256 content ID),
//! HACK_VOLUME_INTEGRITY_IMAGE_ARCHIVE and HACK_VOLUME_INTEGRITY_IMAGE_SHA256.
//! Same-boot reads can use the guest page cache; this does not qualify crash safety,
//! power loss, framework concurrency, or durable readback after VM shutdown.
use super::{options, token};
use crate::provider::graph::*;
use crate::provider::{self, Profile, state::Owner};
use base64::Engine as _;
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::{path::Path, time::Instant};

const BLOCK_BYTES: usize = 1024 * 1024;
const FILE_BYTES: usize = 16 * BLOCK_BYTES;
const NAMES: [&str; 4] = ["corpus-0.bin", "corpus-1.bin", "corpus-2.bin", "atomic.bin"];

#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct FileHashes {
    name: String,
    bytes: usize,
    blocks: Vec<String>,
    whole: String,
}

#[derive(Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(deny_unknown_fields)]
struct Manifest {
    files: Vec<FileHashes>,
}

struct OwnedFixture<'a> {
    candidate: &'a Candidate,
    run: String,
    done: bool,
}

impl Drop for OwnedFixture<'_> {
    fn drop(&mut self) {
        if !self.done {
            if let Err(error) = cleanup(self.candidate, &self.run, false) {
                eprintln!(
                    "Integrity fixture retained graph inspection gate: {}",
                    error.code
                );
            }
            if let Err(error) = provider::down(self.candidate) {
                eprintln!(
                    "Integrity fixture retained VM inspection gate: {}",
                    error.code
                );
            }
        }
    }
}

// Rust SHA-256 and generated bytes are independent of the guest's node:crypto
// implementation. No expected digest is stored in the volume being checked.
fn expected_manifest(atomic_seed: u32) -> Manifest {
    let files = NAMES
        .iter()
        .enumerate()
        .map(|(file, name)| {
            let seed = if file == 3 {
                atomic_seed
            } else {
                file as u32 + 1
            };
            let mut whole = Sha256::new();
            let mut blocks = Vec::new();
            let mut bytes = vec![0; BLOCK_BYTES];
            for block in 0..16 {
                for (within, byte) in bytes.iter_mut().enumerate() {
                    let offset = (block * BLOCK_BYTES + within) as u32;
                    let mut mixed =
                        offset.wrapping_mul(0x045d_9f3b) ^ seed.wrapping_mul(0x9e37_79b9);
                    mixed ^= mixed >> 16;
                    mixed = mixed.wrapping_mul(0x045d_9f3b);
                    mixed ^= mixed >> 16;
                    *byte = mixed as u8;
                }
                blocks.push(format!("{:x}", Sha256::digest(&bytes)));
                whole.update(&bytes);
            }
            FileHashes {
                name: (*name).into(),
                bytes: FILE_BYTES,
                blocks,
                whole: format!("{:x}", whole.finalize()),
            }
        })
        .collect();
    Manifest { files }
}

fn verify(expected: &Manifest, observed: &Manifest) -> Result<(), String> {
    if observed.files.len() != expected.files.len() {
        return Err("file count differs".into());
    }
    for (wanted, actual) in expected.files.iter().zip(&observed.files) {
        if actual.name != wanted.name || actual.bytes != FILE_BYTES || actual.blocks.len() != 16 {
            return Err("file identity or length differs".into());
        }
        for (block, (a, b)) in wanted.blocks.iter().zip(&actual.blocks).enumerate() {
            if a != b {
                return Err(format!("block mismatch {}:{block}", wanted.name));
            }
        }
        if wanted.whole != actual.whole {
            return Err(format!("whole mismatch {}", wanted.name));
        }
    }
    Ok(())
}

const GUEST_IO: &str = r#"
import * as fs from 'node:fs';
import {createHash} from 'node:crypto';
const blockBytes=1048576, fileBytes=16*blockBytes;
const names=['corpus-0.bin','corpus-1.bin','corpus-2.bin','atomic.bin'];
const dir='/data';
if(!fs.lstatSync(dir).isDirectory() || fs.lstatSync(dir).isSymbolicLink()) throw Error('fixture directory');
function syncDir(){const fd=fs.openSync(dir,'r');try{fs.fsyncSync(fd);}finally{fs.closeSync(fd);}}
function writeFile(name,seed){
  const fd=fs.openSync(dir+'/'+name,'wx',0o600);
  try{
    const data=Buffer.alloc(blockBytes);
    for(let block=0;block<16;block++){
      for(let i=0;i<blockBytes;i++){
        let mixed=Math.imul(block*blockBytes+i,0x045d9f3b)^Math.imul(seed,0x9e3779b9);
        mixed^=mixed>>>16;mixed=Math.imul(mixed,0x045d9f3b);mixed^=mixed>>>16;data[i]=mixed&255;
      }
      let written=0;
      while(written<data.length){const n=fs.writeSync(fd,data,written,data.length-written);if(n<=0)throw Error('short write');written+=n;}
    }
    fs.fsyncSync(fd);
  }finally{fs.closeSync(fd);}
}
function replace(seed){
  writeFile('atomic.pending',seed);
  fs.renameSync(dir+'/atomic.pending',dir+'/atomic.bin');syncDir();
}
function readHashes(){
  return {files:names.map(name=>{
    const path=dir+'/'+name, before=fs.lstatSync(path);
    if(!before.isFile() || before.isSymbolicLink() || before.nlink!==1 || before.size!==fileBytes)throw Error('fixture file');
    const fd=fs.openSync(path,'r'), blocks=[], data=Buffer.alloc(blockBytes);
    try{
      for(let block=0;block<16;block++){
        let read=0;
        while(read<blockBytes){const n=fs.readSync(fd,data,read,blockBytes-read,block*blockBytes+read);if(n<=0)throw Error('short read');read+=n;}
        blocks.push(createHash('sha256').update(data).digest('hex'));
      }
      // A separate complete read computes the whole digest, so an unstable second
      // read cannot be hidden by hashing the same block buffers twice.
      const whole=createHash('sha256');
      for(let offset=0;offset<fileBytes;offset+=blockBytes){
        let read=0;
        while(read<blockBytes){const n=fs.readSync(fd,data,read,blockBytes-read,offset+read);if(n<=0)throw Error('short reread');read+=n;}
        whole.update(data);
      }
      const after=fs.lstatSync(path), selected=fs.fstatSync(fd);
      if(after.ino!==before.ino || after.dev!==before.dev || after.size!==before.size || after.mtimeMs!==before.mtimeMs || selected.ino!==before.ino || selected.dev!==before.dev)throw Error('unstable file');
      return {name,bytes:after.size,blocks,whole:whole.digest('hex')};
    }finally{fs.closeSync(fd);}
  })};
}
"#;

fn execute(candidate: &Candidate, receipt: &Receipt, boot: &str, script: &str) -> Value {
    let argv = vec![
        "/usr/local/bin/bun".into(),
        "-e".into(),
        format!("{GUEST_IO}\n{script}"),
    ];
    let result = service_exec(
        candidate,
        ServiceExecOptions {
            run: &receipt.run,
            service: "probe",
            expected_container: receipt.resources["container:probe"].id.as_deref().unwrap(),
            expected_boot: boot,
            expected_generation: &service_exec_generation(receipt).unwrap(),
            argv: &argv,
            workdir: None,
            timeout: Duration::from_secs(30),
        },
    )
    .unwrap();
    assert_eq!(result.exit_code, 0, "synthetic fixture command failed");
    assert!(!result.truncated, "synthetic fixture response truncated");
    assert!(
        result.stderr_base64.is_empty(),
        "synthetic fixture emitted stderr"
    );
    let output = base64::engine::general_purpose::STANDARD
        .decode(result.stdout_base64)
        .unwrap();
    serde_json::from_slice(&output).unwrap()
}

fn read_manifest(candidate: &Candidate, receipt: &Receipt, boot: &str) -> Manifest {
    serde_json::from_value(execute(
        candidate,
        receipt,
        boot,
        "console.log(JSON.stringify(readHashes()));",
    ))
    .unwrap()
}

fn volume_identity(candidate: &Candidate, receipt: &Receipt) -> Value {
    let engine = Engine::connect(candidate).unwrap();
    let volume = inspect_resource(&engine, receipt, &receipt.resources["volume:data"])
        .unwrap()
        .unwrap();
    assert_eq!(volume["Name"], receipt.resources["volume:data"].name);
    assert_eq!(
        volume["Mountpoint"],
        format!(
            "/var/lib/docker/volumes/{}/_data",
            receipt.resources["volume:data"].name
        )
    );
    let directory_identity = engine
        .guest()
        .execute_cleanup(
            "set -eu; test -d \"$1\"; test ! -L \"$1\"; stat -c '%d:%i' \"$1\"",
            &[volume["Mountpoint"].as_str().unwrap()],
        )
        .unwrap();
    assert!(
        directory_identity
            .trim()
            .split_once(':')
            .is_some_and(|(device, inode)| {
                !device.is_empty()
                    && !inode.is_empty()
                    && device
                        .bytes()
                        .chain(inode.bytes())
                        .all(|b| b.is_ascii_digit())
            }),
        "volume directory identity missing"
    );
    json!({"name":volume["Name"],"created":volume["CreatedAt"],"mountpoint":volume["Mountpoint"],"directory_device_inode":directory_identity.trim(),"driver":volume["Driver"],"labels":volume["Labels"],"options":volume["Options"],"scope":volume["Scope"]})
}

fn assert_same_provider(candidate: &Candidate, initial: &Owner, boot: &str) {
    let status = provider::status(candidate).unwrap();
    assert_eq!(status.phase, "running");
    assert_eq!(status.guest_boot_id.as_deref(), Some(boot));
    let current = Owner::load(candidate).unwrap();
    assert_eq!(current.process, initial.process);
    assert_eq!(current.storage, initial.storage);
    assert_eq!(current.overlay, initial.overlay);
    assert_eq!(current.token, initial.token);
}

fn require_virgin(candidate: &Candidate) {
    let run = candidate.state_root.join("run");
    if !run.try_exists().unwrap() {
        return;
    }
    state::check_private_directory(&run).unwrap();
    let entries = |path: &Path| {
        fs::read_dir(path)
            .unwrap()
            .map(|entry| entry.unwrap().file_name())
            .collect::<Vec<_>>()
    };
    assert_eq!(
        entries(&run),
        vec![std::ffi::OsString::from("smolvm")],
        "fixture home contains non-preparation state"
    );
    let provider = run.join("smolvm");
    let _lock = state::Lock::acquire_existing(&provider).unwrap();
    assert_eq!(
        entries(&provider),
        vec![std::ffi::OsString::from("operation.lock")],
        "fixture home contains prior runtime state"
    );
    assert_eq!(
        fs::metadata(provider.join("operation.lock")).unwrap().len(),
        0,
        "preparation lock contains unexpected data"
    );
}

#[test]
#[ignore = "Virgin private prepared home, hashed local Bun archive and external 300-second watchdog required"]
fn owned_named_volume_integrity_survives_container_restart() {
    let began = Instant::now();
    let root = std::env::var("HACK_VOLUME_INTEGRITY_ROOT")
        .expect("explicit virgin private candidate home");
    let candidate = Candidate::discover_installed(Path::new(&root)).unwrap();
    let source_root = Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .canonicalize()
        .unwrap();
    assert!(
        !candidate.checkout.starts_with(&source_root)
            && !source_root.starts_with(&candidate.checkout),
        "fixture home must be outside repository checkouts"
    );
    require_virgin(&candidate);
    assert_eq!(provider::status(&candidate).unwrap().phase, "uninitialized");
    let image = std::env::var("HACK_VOLUME_INTEGRITY_IMAGE").expect("pinned Bun image content ID");
    assert!(image_id(&image), "pinned image content ID required");
    let archive = std::env::var("HACK_VOLUME_INTEGRITY_IMAGE_ARCHIVE")
        .expect("explicit local Bun image archive");
    let archive_sha = std::env::var("HACK_VOLUME_INTEGRITY_IMAGE_SHA256")
        .expect("explicit image archive SHA-256");
    assert!(hex(&archive_sha, 64), "archive SHA-256 required");
    let fixture = super::super::super::tests::Fixture::new();
    let run_id = token();
    let mut guard = OwnedFixture {
        candidate: &candidate,
        run: run_id.clone(),
        done: false,
    };
    let evidence_dir = candidate.state_root.join("review/volume-integrity");
    state::private_directory(&evidence_dir).unwrap();
    let evidence_path = evidence_dir.join(format!("{run_id}.json"));
    state::write(&evidence_path, &json!({"phase":"intent","run":run_id,"bytes":4*FILE_BYTES,"block_bytes":BLOCK_BYTES,"boundary":"container-only; no VM shutdown qualification"})).unwrap();
    let initial = provider::up_with_profile(&candidate, Profile::Development).unwrap();
    assert_eq!(initial.phase, "running");
    assert_eq!(initial.network, Some(provider::NetworkIntent::Isolated));
    assert!(initial.application_bridge.is_none() && initial.dependency_sockets.is_none());
    let boot = initial.guest_boot_id.unwrap();
    let owner = Owner::load(&candidate).unwrap();
    assert!(owner.process.is_some() && owner.storage.is_some() && owner.overlay.is_some());
    provider::load_image(&candidate, Path::new(&archive), &archive_sha, &image).unwrap();
    state::write(&fixture.0.join("compose.yaml"), &json!({
        "services":{"probe":{
            "image":image,"read_only":true,"network_mode":"none","user":"0:0","init":true,
            "entrypoint":["/usr/local/bin/bun","-e","process.on('SIGTERM',()=>process.exit(0));setInterval(()=>{},1000);"],"command":[],
            "mem_limit":"256m","pids_limit":32,"stop_signal":"SIGTERM","stop_grace_period":"2s","volumes":["data:/data"]
        }},"volumes":{"data":{}}
    })).unwrap();
    let plan = project::plan(&candidate, options(&fixture.0)).unwrap();
    let readiness = BTreeMap::from([("probe".into(), Condition::Started)]);
    let public_values = BTreeMap::new();
    let run_options = || RunOptions {
        live_source: false,
        shared_source: false,
        release_initializer_cache: BTreeSet::new(),
        routing_enrolled: false,
        project: options(&fixture.0),
        expected_plan: &plan.plan_id,
        source_revision: None,
        non_secret_values: &public_values,
        readiness: &readiness,
        run_id: &run_id,
        timeout: Duration::from_secs(30),
    };
    let mut receipt = run(&candidate, run_options()).unwrap();
    let container_id = receipt.resources["container:probe"].id.clone();
    let volume = volume_identity(&candidate, &receipt);
    assert_eq!(
        execute(
            &candidate,
            &receipt,
            &boot,
            "if(fs.readdirSync(dir).length!==0)throw Error('nonempty fixture');for(let i=0;i<3;i++)writeFile(names[i],i+1);syncDir();replace(64);replace(128);console.log(JSON.stringify({written:4*fileBytes}));"
        )["written"],
        4 * FILE_BYTES
    );
    let mut expected = expected_manifest(128);
    let first = read_manifest(&candidate, &receipt, &boot);
    verify(&expected, &first).unwrap();
    let mut observations = vec![json!({"phase":"initial","manifest":first})];
    for cycle in 1..=2 {
        {
            let engine = Engine::connect(&candidate).unwrap();
            let (selected, graph_root) = load(&candidate, &engine, &run_id).unwrap();
            super::super::stop_owned(&engine, &selected, &graph_root).unwrap();
            let container =
                inspect_resource(&engine, &selected, &selected.resources["container:probe"])
                    .unwrap()
                    .unwrap();
            assert_eq!(container["State"]["Status"], "exited");
            assert_eq!(container["State"]["ExitCode"], 0);
            assert_eq!(container["State"]["OOMKilled"], false);
        }
        assert_same_provider(&candidate, &owner, &boot);
        receipt = restart(&candidate, run_options()).unwrap();
        assert_eq!(receipt.resources["container:probe"].id, container_id);
        assert_eq!(volume_identity(&candidate, &receipt), volume);
        assert_same_provider(&candidate, &owner, &boot);
        let retained = read_manifest(&candidate, &receipt, &boot);
        verify(&expected, &retained).unwrap();
        observations.push(
            json!({"phase":"retained-after-container-restart","cycle":cycle,"manifest":retained}),
        );
        let seed = 128 + cycle;
        assert_eq!(
            execute(
                &candidate,
                &receipt,
                &boot,
                &format!("replace({seed});console.log(JSON.stringify({{replaced:{seed}}}));")
            )["replaced"],
            seed
        );
        expected = expected_manifest(seed);
        let replaced = read_manifest(&candidate, &receipt, &boot);
        verify(&expected, &replaced).unwrap();
        observations.push(json!({"phase":"atomic-replacement","cycle":cycle,"manifest":replaced}));
        state::write(&evidence_path, &json!({"phase":"positive-cycle-complete","run":run_id,"boot":boot,"provider_process":owner.process,"volume":volume,"observations":observations})).unwrap();
    }
    assert_eq!(
        execute(
            &candidate,
            &receipt,
            &boot,
            "const fd=fs.openSync(dir+'/corpus-1.bin','r+');try{const data=Buffer.alloc(1),offset=7*blockBytes+37;if(fs.readSync(fd,data,0,1,offset)!==1)throw Error('negative read');data[0]^=1;if(fs.writeSync(fd,data,0,1,offset)!==1)throw Error('negative write');fs.fsyncSync(fd);}finally{fs.closeSync(fd);}syncDir();console.log(JSON.stringify({flipped:1}));"
        )["flipped"],
        1
    );
    let corrupted = read_manifest(&candidate, &receipt, &boot);
    assert_eq!(
        verify(&expected, &corrupted).unwrap_err(),
        "block mismatch corpus-1.bin:7"
    );
    for (file, (wanted, actual)) in expected.files.iter().zip(&corrupted.files).enumerate() {
        assert_eq!(actual.name, wanted.name);
        assert_eq!(actual.bytes, wanted.bytes);
        assert_eq!(actual.blocks.len(), wanted.blocks.len());
        for (block, (a, b)) in wanted.blocks.iter().zip(&actual.blocks).enumerate() {
            assert_eq!(
                a != b,
                file == 1 && block == 7,
                "negative control changed an unexpected block"
            );
        }
        assert_eq!(
            wanted.whole != actual.whole,
            file == 1,
            "whole hash did not independently detect the negative control"
        );
    }
    assert_same_provider(&candidate, &owner, &boot);
    assert_eq!(volume_identity(&candidate, &receipt), volume);
    state::write(&evidence_path, &json!({"phase":"integrity-qualified-before-VM-shutdown","run":run_id,"boot":boot,"provider_process":owner.process,"volume":volume,"observations":observations,"negative_control":"one changed byte rejected; exactly block corpus-1.bin:7 and its whole digest differ","negative_manifest":corrupted})).unwrap();
    cleanup(&candidate, &run_id, true).unwrap();
    {
        let engine = Engine::connect(&candidate).unwrap();
        for resource in receipt.resources.values() {
            assert!(
                inspect_resource(&engine, &receipt, resource)
                    .unwrap()
                    .is_none(),
                "owned fixture resource remained after cleanup"
            );
        }
    }
    assert_same_provider(&candidate, &owner, &boot);
    assert_eq!(
        provider::down(&candidate).unwrap().process_alive,
        Some(false)
    );
    guard.done = true;
    assert!(
        began.elapsed() < Duration::from_secs(240),
        "fixture exceeded its bounded qualification window"
    );
    println!(
        "64 MiB volume: two container-only cycles retained exact identities and independent block/whole hashes; atomic replacement and one-byte negative control passed; owned resources removed and VM stopped; evidence {}",
        evidence_path.display()
    );
}
