import "../../apps/web/tests/package-manifest.test.ts";
import "../../apps/web/tests/auth-entrypoints.test.tsx";
import "../../apps/web/tests/auth-handoff.test.ts";
import "../../apps/web/tests/control-plane-shell.test.tsx";
import "../../apps/web/tests/account-shell.test.tsx";
import "../../apps/web/tests/project-control-plane-render.test.tsx";
import "../../apps/web/tests/project-control-plane-routes.test.ts";
import "../../apps/web/tests/project-control-plane.test.ts";
import "../../apps/web/tests/linear-management.test.ts";
