import { verifyFiniteModelResult } from "./tla-result.ts";

type ModelResult = {
  readonly negative: boolean;
  readonly exitCode: number | null;
  readonly output: string;
};
type ModelWitness = {
  readonly action: string;
  readonly fields: readonly string[];
};
type ModelContract = {
  readonly name: string;
  readonly module: string;
  readonly negativeModule?: string;
  readonly states: number;
  readonly invariant: string;
  readonly action: string;
  readonly fields: readonly string[];
  readonly alternativeWitnesses?: readonly ModelWitness[];
  readonly additionalControls?: readonly {
    readonly name: string;
    readonly module?: "TerminalReuse";
    readonly negative: boolean;
    readonly states?: number;
    readonly invariant?: string;
    readonly action?: string;
    readonly fields?: readonly string[];
    readonly alternativeWitnesses?: readonly ModelWitness[];
  }[];
};

// Bounds and witnesses are reviewed contracts, not learned from each run.
const laterIncompleteMissingLockStages = [
  "temp",
  "linked",
  "final",
  "journal",
  "socket",
  "owner",
] as const;
const contracts: readonly ModelContract[] = [
  {
    name: "native-storage-witness",
    module: "Witness",
    states: 352,
    invariant: "NoSeedOnReopen",
    action: "SeedOnResume",
    fields: [
      'operation = "resume"',
      "expected = 1",
      "enrolled = 1",
      "metadata = 1",
      "marker = 1",
      "seedWrites = 2",
      "enrollmentWrites = 1",
      "seedCapability = FALSE",
      "completionCapability = FALSE",
      "unsafeSeed = TRUE",
    ],
    additionalControls: [
      {
        name: "missing-witness",
        negative: true,
        invariant: "NoWorkloadWithoutWitness",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          "expected = 1",
          "enrolled = 1",
          "metadata = 1",
          "marker = 0",
          "unsafeStart = TRUE",
        ],
      },
      {
        name: "wrong-witness",
        negative: true,
        invariant: "NoWorkloadWithoutWitness",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          "expected = 1",
          "enrolled = 1",
          "metadata = 1",
          "marker = 2",
          "unsafeStart = TRUE",
        ],
      },
      {
        name: "foreign-metadata",
        negative: true,
        invariant: "NoWorkloadWithoutWitness",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          "expected = 1",
          "enrolled = 1",
          "metadata = 2",
          "marker = 1",
          "unsafeStart = TRUE",
        ],
      },
      {
        name: "premature-completion",
        negative: true,
        invariant: "NoUnprovedCompletion",
        action: "CommitEnrollment",
        fields: [
          'phase = "enrolled"',
          "expected = 1",
          "enrolled = 1",
          "metadata = 1",
          "marker = 0",
          "unsafeCompletion = TRUE",
        ],
      },
      {
        name: "expectation-replacement",
        negative: true,
        invariant: "NoChangedExpectation",
        action: "ReplaceExpectation",
        fields: [
          'phase = "checking"',
          "expected = 2",
          "originalExpected = 1",
          "enrolled = 1",
          "unsafeReplacement = TRUE",
        ],
      },
      {
        name: "readonly-reenrollment",
        negative: true,
        invariant: "NoReadOnlyReenrollment",
        action: "ReenrollReadOnly",
        fields: [
          'phase = "checked"',
          "expected = 1",
          "enrolled = 1",
          "marker = 1",
          "enrollmentWrites = 2",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeReenrollment = TRUE",
        ],
      },
      {
        name: "recovery-seed",
        negative: true,
        invariant: "NoSeedOnReopen",
        action: "SeedOnRecovery",
        fields: [
          'phase = "interrupted"',
          'operation = "recovery"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 0",
          "volumePresent = TRUE",
          "marker = 1",
          "seedWrites = 1",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeSeed = TRUE",
        ],
      },
      {
        name: "cold-reachable",
        negative: true,
        invariant: "NeverColdWorkload",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          'operation = "cold"',
          "expected = 1",
          "enrolled = 1",
          "marker = 1",
          "metadata = 1",
          "seedWrites = 1",
          "enrollmentWrites = 1",
          "unsafeStart = FALSE",
          "unsafeCompletion = FALSE",
        ],
      },
      {
        name: "resume-reachable",
        negative: true,
        invariant: "NeverReadOnlyResume",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          'operation = "resume"',
          "expected = 1",
          "enrolled = 1",
          "marker = 1",
          "metadata = 1",
          "resumes = 1",
          "seedWrites = 1",
          "enrollmentWrites = 1",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeSeed = FALSE",
          "unsafeStart = FALSE",
        ],
      },
      {
        name: "recovery-reachable",
        negative: true,
        invariant: "NeverEnrolledRecovery",
        action: "StartWorkload",
        fields: [
          'phase = "running"',
          'operation = "recovery"',
          "expected = 1",
          "enrolled = 1",
          "marker = 1",
          "metadata = 1",
          "crashes = 1",
          "seedWrites = 1",
          "enrollmentWrites = 1",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeSeed = FALSE",
          "unsafeStart = FALSE",
        ],
      },
      {
        name: "empty-intent-refusal-reachable",
        negative: true,
        invariant: "NeverEmptyIntentRefusal",
        action: "RecoveryDisposition",
        fields: [
          'phase = "refused"',
          'operation = "recovery"',
          'disposition = "needs-explicit-reconcile"',
          "intent = TRUE",
          "expected = 0",
          "originalExpected = 0",
          "enrolled = 0",
          "volumePresent = FALSE",
          "marker = 0",
          "seedWrites = 0",
          "enrollmentWrites = 0",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
        ],
      },
      {
        name: "interrupted-missing-reachable",
        negative: true,
        invariant: "NeverInterruptedMissingRefusal",
        action: "RecoveryDisposition",
        fields: [
          'phase = "refused"',
          'operation = "recovery"',
          'disposition = "needs-explicit-reconcile"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 0",
          "volumePresent = TRUE",
          "metadata = 1",
          "marker = 0",
          "seedWrites = 0",
          "enrollmentWrites = 0",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
        ],
      },
      {
        name: "interrupted-matching-reachable",
        negative: true,
        invariant: "NeverInterruptedMatchingRefusal",
        action: "RecoveryDisposition",
        fields: [
          'phase = "refused"',
          'operation = "recovery"',
          'disposition = "needs-explicit-reconcile"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 0",
          "volumePresent = TRUE",
          "metadata = 1",
          "marker = 1",
          "seedWrites = 1",
          "enrollmentWrites = 0",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
        ],
      },
      {
        name: "missing-resume-refusal-reachable",
        negative: true,
        invariant: "NeverMissingResumeRefusal",
        action: "RefuseResume",
        fields: [
          'phase = "refused"',
          'operation = "resume"',
          'disposition = "witness-mismatch"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 1",
          "metadata = 1",
          "marker = 0",
          "seedWrites = 1",
          "enrollmentWrites = 1",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeStart = FALSE",
          "unsafeSeed = FALSE",
        ],
      },
      {
        name: "wrong-resume-refusal-reachable",
        negative: true,
        invariant: "NeverWrongResumeRefusal",
        action: "RefuseResume",
        fields: [
          'phase = "refused"',
          'operation = "resume"',
          'disposition = "witness-mismatch"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 1",
          "metadata = 1",
          "marker = 2",
          "seedWrites = 1",
          "enrollmentWrites = 1",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
          "unsafeStart = FALSE",
          "unsafeSeed = FALSE",
        ],
      },
      {
        name: "stale-proof-refusal-reachable",
        negative: true,
        invariant: "NeverStaleProofRefusal",
        action: "RefuseEnrollment",
        fields: [
          'phase = "refused"',
          'operation = "cold"',
          'disposition = "needs-explicit-reconcile"',
          "expected = 1",
          "originalExpected = 1",
          "enrolled = 0",
          "metadata = 1",
          "marker = 0",
          "proof = TRUE",
          "unsafeCompletion = FALSE",
        ],
      },
      {
        name: "legacy-refusal-reachable",
        negative: true,
        invariant: "NeverLegacyRefusal",
        action: "RefuseLegacy",
        fields: [
          'phase = "refused"',
          'disposition = "needs-adoption"',
          "expected = 0",
          "originalExpected = 0",
          "enrolled = 0",
          "volumePresent = TRUE",
          "seedWrites = 0",
          "enrollmentWrites = 0",
          "seedCapability = FALSE",
          "completionCapability = FALSE",
        ],
      },
    ],
  },
  {
    name: "native-file-material",
    module: "Material",
    states: 8388,
    invariant: "NoLostRecovery",
    action: "CommitStop",
    fields: [
      'generation = "stopped"',
      "recoveryReference = FALSE",
      "members = {1, 2}",
      'retirement = "live"',
      'phase = "complete"',
    ],
    additionalControls: [
      {
        name: "unproved-absence",
        negative: true,
        invariant: "NoUnprovedDeletion",
        action: "DeleteMember",
        fields: [
          'phase = "retiring"',
          'retirement = "intent"',
          "containerPresent = TRUE",
          "unsafeDelete = TRUE",
        ],
      },
      {
        name: "uncertain-hook",
        negative: true,
        invariant: "NoUnprovedDeletion",
        action: "DeleteMember",
        fields: [
          'phase = "retiring"',
          "hookPending = TRUE",
          "childPending = FALSE",
          "unsafeDelete = TRUE",
        ],
      },
      {
        name: "unknown-child",
        negative: true,
        invariant: "NoUnprovedDeletion",
        action: "DeleteMember",
        fields: [
          'phase = "retiring"',
          "hookPending = FALSE",
          "childPending = TRUE",
          "unsafeDelete = TRUE",
        ],
      },
      {
        name: "unknown-stop-child",
        negative: true,
        invariant: "NoUnprovedDeletion",
        action: "DeleteMember",
        fields: [
          'phase = "retiring"',
          'stopChild = "unknown"',
          "childPending = FALSE",
          "hookPending = FALSE",
          "unsafeDelete = TRUE",
        ],
      },
      {
        name: "stale-reference",
        negative: true,
        invariant: "NoUnprovedDeletion",
        action: "DeleteMember",
        fields: [
          'phase = "retiring"',
          "anchorVersion = 2",
          "ownerVersion = 1",
          "pendingVersion = 1",
          "unsafeDelete = TRUE",
        ],
      },
      {
        name: "stale-finalizer-owner",
        negative: true,
        invariant: "NoStaleCompletion",
        action: "CommitStop",
        fields: [
          'phase = "complete"',
          'retirement = "retired"',
          "members = {}",
          "ownerVersion = 2",
          "pendingVersion = 1",
          "unsafeCommit = TRUE",
        ],
      },
      {
        name: "stale-finalizer-pending",
        negative: true,
        invariant: "NoStaleCompletion",
        action: "CommitStop",
        fields: [
          'phase = "complete"',
          'retirement = "retired"',
          "members = {}",
          "ownerVersion = 1",
          "pendingVersion = 2",
          "unsafeCommit = TRUE",
        ],
      },
      {
        name: "missing-without-intent",
        negative: true,
        invariant: "NoInferredIntent",
        action: "BeginRetirement",
        fields: [
          'phase = "retiring"',
          'retirement = "intent"',
          "missingWithoutIntent = TRUE",
          "unsafeIntent = TRUE",
        ],
      },
      {
        name: "partial-crash-reachable",
        negative: true,
        invariant: "NeverCompleteAfterPartialCrash",
        action: "CommitStop",
        fields: [
          'generation = "stopped"',
          'retirement = "retired"',
          "members = {}",
          "partialCrash = TRUE",
          "crashes = 1",
          "unsafeCommit = FALSE",
        ],
      },
      {
        name: "missing-source-reachable",
        negative: true,
        invariant: "NeverCompleteWithoutSource",
        action: "CommitStop",
        fields: [
          'generation = "stopped"',
          'retirement = "retired"',
          "members = {}",
          "sourceFresh = FALSE",
          "unsafeCommit = FALSE",
        ],
      },
    ],
  },
  {
    name: "native-route-stop",
    module: "Stop",
    states: 202,
    invariant: "NoLostRecovery",
    action: "CommitStop",
    fields: [
      'generation = "stopped"',
      'phase = "complete"',
      "claimHeld = TRUE",
      "workloadPresent = FALSE",
    ],
    additionalControls: [
      {
        name: "unproved-retirement",
        negative: true,
        invariant: "NoUnprovedRelease",
        action: "RetireClaims",
        fields: [
          'phase = "released"',
          "claimHeld = FALSE",
          "absenceObserved = FALSE",
          "unsafeRelease = TRUE",
        ],
      },
      {
        name: "stale-reference",
        negative: true,
        invariant: "NoUnprovedRelease",
        action: "RetireClaims",
        fields: [
          'phase = "released"',
          "claimHeld = FALSE",
          "absenceObserved = TRUE",
          "selected = 1",
          "version = 2",
          "unsafeRelease = TRUE",
        ],
      },
      {
        name: "uncertain-hook",
        negative: true,
        invariant: "NoUnprovedRelease",
        action: "RetireClaims",
        fields: [
          'phase = "released"',
          "claimHeld = FALSE",
          "absenceObserved = TRUE",
          "hookPending = TRUE",
          "unsafeRelease = TRUE",
        ],
      },
      {
        name: "completion-reachable",
        negative: true,
        invariant: "NeverComplete",
        action: "CommitStop",
        fields: [
          'generation = "stopped"',
          'phase = "complete"',
          "claimHeld = FALSE",
          "workloadPresent = FALSE",
          "routePresent = FALSE",
          "hookPending = FALSE",
          "unsafeRelease = FALSE",
        ],
      },
    ],
  },
  {
    name: "registry-writer",
    module: "RegistryWriter",
    states: 7721,
    invariant: "NoLiveOwnershipLoss",
    action: "Reap",
    fields: ["unsafeReap = TRUE", "lock = 0", "guard = 0"],
  },
  {
    name: "absent-publication-recovery",
    module: "Absent",
    states: 247,
    invariant: "NoPrematurePublication",
    action: "Publish",
    fields: [
      "intent = TRUE",
      "complete = FALSE",
      "retired = FALSE",
      "published = TRUE",
      "unsafePublication = TRUE",
    ],
    additionalControls: [
      {
        name: "unwitnessed-cleanup",
        negative: true,
        invariant: "NoUnwitnessedCleanup",
        action: "CleanupOne",
        fields: [
          "intent = FALSE",
          "progress = 1",
          'engine = "recovery"',
          'foreground = "recovery"',
          "unsafeCleanup = TRUE",
        ],
      },
      {
        name: "stale-selection",
        negative: true,
        invariant: "NoUnwitnessedCleanup",
        action: "CleanupOne",
        fields: [
          "intent = TRUE",
          "selected = 1",
          "version = 2",
          "progress = 1",
          "unsafeCleanup = TRUE",
        ],
      },
      {
        name: "unconfirmed-retirement",
        negative: true,
        invariant: "NoUnconfirmedRetirement",
        action: "RetireAbsentPublisher",
        fields: [
          "intent = FALSE",
          "complete = FALSE",
          "progress = 0",
          "retired = TRUE",
          "unsafeRetirement = TRUE",
        ],
      },
    ],
  },
  {
    name: "missing-publication-lock",
    module: "MissingLock",
    states: 96,
    invariant: "NoPrematureConsumer",
    action: "AdmitOrdinary",
    fields: [
      'stage = "owner"',
      'consumer = "ordinary"',
      "gate = FALSE",
      "unsafeAdmission = TRUE",
    ],
    additionalControls: [
      {
        name: "retired-admission",
        negative: true,
        invariant: "NoPrematureConsumer",
        action: "AdmitRetired",
        fields: [
          'stage = "owner"',
          'consumer = "retired"',
          "gate = FALSE",
          "unsafeAdmission = TRUE",
        ],
      },
      {
        name: "stale-proof",
        negative: true,
        invariant: "NoUnprovedCompletion",
        action: "Commit",
        fields: [
          'stage = "complete"',
          "selected = 1",
          "version = 2",
          "unsafeCompletion = TRUE",
        ],
      },
      {
        name: "replaced-lock",
        negative: true,
        invariant: "NoUnprovedCompletion",
        action: "Commit",
        fields: [
          'stage = "complete"',
          'lockPath = "foreign"',
          "unsafeCompletion = TRUE",
        ],
      },
      {
        name: "old-holder",
        negative: true,
        invariant: "NoUncoordinatedLegacy",
        action: "OldHolderPublish",
        fields: [
          'stage = "intent"',
          'repair = "active"',
          "gate = TRUE",
          "legacyPublished = TRUE",
        ],
        alternativeWitnesses: laterIncompleteMissingLockStages.map((stage) => ({
          action: "OldHolderPublish",
          fields: [
            `stage = "${stage}"`,
            'repair = "active"',
            "gate = TRUE",
            "legacyPublished = TRUE",
          ],
        })),
      },
      {
        name: "completion-reachable",
        negative: true,
        invariant: "NeverComplete",
        action: "Commit",
        fields: [
          'stage = "complete"',
          'lockPath = "replacement"',
          "unsafeCompletion = FALSE",
        ],
      },
    ],
  },
  {
    name: "shared-https-lifetime",
    module: "SharedHttps",
    states: 64,
    invariant: "NoPrematureShutdown",
    action: "FinishClose",
    fields: ['mode = "closed"', "leases = {2}", "unsafeShutdown = TRUE"],
  },
  {
    name: "previous-boot-shared-https",
    module: "ArchiveHttps",
    states: 92,
    invariant: "NoPrematurePublication",
    action: "Publish",
    fields: [
      "intent = TRUE",
      "complete = FALSE",
      'archived = {"owner"}',
      "crashed = TRUE",
      "published = TRUE",
      "unsafePublication = TRUE",
    ],
    alternativeWitnesses: [
      {
        action: "Publish",
        fields: [
          "intent = TRUE",
          "complete = FALSE",
          'archived = {"owner", "socket"}',
          "crashed = TRUE",
          "published = TRUE",
          "unsafePublication = TRUE",
        ],
      },
    ],
    additionalControls: [
      {
        name: "stale-selection",
        negative: true,
        invariant: "NoUnprovedArchive",
        action: "ArchiveOwner",
        fields: [
          "intent = TRUE",
          "selected = 1",
          "version = 2",
          "engine = TRUE",
          'admission = "recovery"',
          'archived = {"owner"}',
          "unsafeArchive = TRUE",
        ],
        alternativeWitnesses: [
          {
            action: "ArchiveOwner",
            fields: [
              "intent = TRUE",
              "selected = 1",
              "version = 2",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"owner", "socket"}',
              "unsafeArchive = TRUE",
            ],
          },
          {
            action: "ArchiveSocket",
            fields: [
              "intent = TRUE",
              "selected = 1",
              "version = 2",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"socket"}',
              "unsafeArchive = TRUE",
            ],
          },
          {
            action: "ArchiveSocket",
            fields: [
              "intent = TRUE",
              "selected = 1",
              "version = 2",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"owner", "socket"}',
              "unsafeArchive = TRUE",
            ],
          },
        ],
      },
      {
        name: "unproved-archive",
        negative: true,
        invariant: "NoUnprovedArchive",
        action: "ArchiveOwner",
        fields: [
          "intent = TRUE",
          "eligible = FALSE",
          "engine = TRUE",
          'admission = "recovery"',
          'archived = {"owner"}',
          "unsafeArchive = TRUE",
        ],
        alternativeWitnesses: [
          {
            action: "ArchiveOwner",
            fields: [
              "intent = TRUE",
              "eligible = FALSE",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"owner", "socket"}',
              "unsafeArchive = TRUE",
            ],
          },
          {
            action: "ArchiveSocket",
            fields: [
              "intent = TRUE",
              "eligible = FALSE",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"socket"}',
              "unsafeArchive = TRUE",
            ],
          },
          {
            action: "ArchiveSocket",
            fields: [
              "intent = TRUE",
              "eligible = FALSE",
              "engine = TRUE",
              'admission = "recovery"',
              'archived = {"owner", "socket"}',
              "unsafeArchive = TRUE",
            ],
          },
        ],
      },
    ],
  },
  {
    name: "stopped-pool-startup",
    module: "Resume",
    states: 71,
    invariant: "NoSubstitutedBoot",
    action: "Boot",
    fields: [
      'phase = "pending"',
      "attempts = 1",
      "bootSelectionMatched = FALSE",
      "selectedOwner = 1",
      "selectedReceipt = 1",
      "locked = TRUE",
    ],
    additionalControls: [
      {
        name: "uncertain-replay",
        negative: true,
        invariant: "NoUncertainReplay",
        action: "Retry",
        fields: [
          'phase = "pending"',
          "attempts = 2",
          "uncertain = TRUE",
          "bootSelectionMatched = TRUE",
          "authority = FALSE",
          "locked = TRUE",
        ],
      },
    ],
  },
  {
    name: "dependency-rebind",
    module: "Rebind",
    states: 21,
    invariant: "NoEarlyAdmission",
    action: "Release",
    fields: [
      'phase = "active"',
      "admitted = TRUE",
      "revoked = {}",
      "streams = {1, 2}",
      "committed = FALSE",
    ],
    additionalControls: [
      { name: "mixed-completed", negative: false, states: 19 },
      { name: "all-completed", negative: false, states: 18 },
      { name: "refused-readiness", negative: false, states: 2 },
      { name: "refused-failed-completed", negative: false, states: 2 },
      {
        name: "terminal-reuse",
        module: "TerminalReuse",
        negative: false,
        states: 82,
      },
      {
        name: "premature-terminal-reuse",
        module: "TerminalReuse",
        negative: true,
        invariant: "NoPrematureNewGrant",
        action: "RegisterNew",
        fields: [
          'phase = "one-off"',
          "grants = {3}",
          "committed = FALSE",
          "slotReady = FALSE",
          "fenced = TRUE",
        ],
      },
      {
        name: "wrong-readiness",
        negative: true,
        invariant: "NoWrongTerminalReadiness",
        action: "Review",
        fields: [
          'phase = "reviewed"',
          "completed = {2}",
          "reviewed = TRUE",
          "admitted = FALSE",
        ],
      },
      {
        name: "failed-completed",
        negative: true,
        invariant: "NoWrongTerminalReadiness",
        action: "Review",
        fields: [
          'phase = "reviewed"',
          "completed = {2}",
          "reviewed = TRUE",
          "admitted = FALSE",
        ],
      },
    ],
  },
  {
    name: "relay-lifecycle-barrier",
    module: "Barrier",
    states: 1590,
    invariant: "NoUnretiredTarget",
    action: "BeginEffect",
    fields: [
      "unsafeCommit = TRUE",
      'phase = "effect-started"',
      "journal = TRUE",
      "ownerAlive = TRUE",
      "connections = {1, 2}",
    ],
  },
  {
    name: "relay-authorization",
    module: "Authorization",
    states: 7,
    invariant: "NoLateWrite",
    action: "Write",
    fields: ["active = FALSE", "lateWrite = TRUE", 'phase = "done"'],
  },
  {
    name: "mcp-startup-cancellation",
    module: "Cancellation",
    states: 10,
    invariant: "NoLatePublication",
    action: "Publish",
    fields: ["cancelled = TRUE", "latePublication = TRUE"],
  },
  {
    name: "mcp-startup",
    module: "Startup",
    states: 27,
    invariant: "NoRevokedGrant",
    action: "Timeout",
    fields: ["granted = TRUE", "killed = TRUE"],
  },
  {
    name: "authority-snapshot",
    module: "Routing",
    states: 11,
    invariant: "NoWrongReservation",
    action: "Connect",
    fields: ["observed = 1", "delivered = 2"],
  },
  {
    name: "authority-lifetime",
    module: "Lifetime",
    states: 9,
    invariant: "NoAuthorityAfterDown",
    action: "StartBind",
    fields: ["running = FALSE", "authority = TRUE"],
  },
  {
    name: "publication-journal",
    module: "Journal",
    states: 50,
    invariant: "Safe",
    action: "Recover",
    fields: ["alive = TRUE", "recoveredLive = TRUE"],
  },
  {
    name: "publication",
    module: "Publication",
    states: 16,
    invariant: "Safe",
    action: "Retire",
    fields: ['process = "native"', "intent = FALSE"],
  },
  {
    name: "fence-first",
    module: "First",
    negativeModule: "FirstBroken",
    states: 24,
    invariant: "Safe",
    action: "Recover",
    fields: ["occupied = TRUE", "recovered = TRUE"],
  },
  {
    name: "fence-pending",
    module: "Fence",
    negativeModule: "FenceBroken",
    states: 7,
    invariant: "Safe",
    action: "Recover",
    fields: ['phase = "stopped"', "alive = TRUE"],
  },
  {
    name: "relay-staging",
    module: "Stage",
    negativeModule: "StageBroken",
    states: 9,
    invariant: "Safe",
    action: "Discard",
    fields: ['phase = "discarded"', "alive = TRUE"],
  },
  {
    name: "relay-fence",
    module: "RelayFence",
    negativeModule: "RelayFenceBroken",
    states: 16,
    invariant: "Safe",
    action: "Launch",
    fields: ["retired = <<1>>", "alive = 1"],
  },
];

export const runtimeModels = contracts.map((contract) => ({
  ...contract,
  verify: (result: ModelResult) =>
    verifyFiniteModelResult({ ...result, ...contract }),
  additionalControls: (contract.additionalControls ?? []).map((control) => {
    const selected = {
      ...control,
      states: control.states ?? contract.states,
      invariant: control.invariant ?? contract.invariant,
      action: control.action ?? contract.action,
      fields: control.fields ?? contract.fields,
    };
    return {
      ...selected,
      verify: (result: ModelResult) =>
        verifyFiniteModelResult({ ...selected, ...result }),
    };
  }),
}));

/** Config names are fixed case metadata, never filesystem paths. */
export function runtimeModelControlConfig(name: string): string {
  if (!/^[a-z][a-z0-9-]{0,63}$/.test(name)) {
    throw new Error("Invalid runtime model control name.");
  }
  return `${name}.cfg`;
}
