import { unlink } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  ensureDir,
  pathExists,
  readTextFile,
  writeTextFileIfChanged,
} from "../lib/fs.ts";

export type CursorScope = "project" | "user";

export type CursorRulesResult = {
  readonly scope: CursorScope;
  readonly status:
    | "created"
    | "updated"
    | "noop"
    | "removed"
    | "missing"
    | "error";
  readonly path: string;
  readonly message?: string;
};

const RULES_FILENAME = "hack.mdc";
const RULES_DIR = ".cursor/rules";
const MARKER_START = "# BEGIN HACK INTEGRATION";
const MARKER_END = "# END HACK INTEGRATION";

/**
 * Install or update Cursor rules for hack CLI usage.
 */
export async function installCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  const existed = await pathExists(path);
  await ensureDir(dirname(path));
  const result = await writeTextFileIfChanged(path, renderCursorRules());

  const status = resolveInstallStatus({ changed: result.changed, existed });
  return { scope: opts.scope, status, path };
}

/**
 * Check whether Cursor rules are installed.
 */
export async function checkCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  const content = await readTextFile(path);
  if (!content) {
    return { scope: opts.scope, status: "missing", path };
  }

  if (!content.includes(MARKER_START)) {
    return {
      scope: opts.scope,
      status: "error",
      path,
      message: "Rules file exists but is missing hack integration markers.",
    };
  }

  return { scope: opts.scope, status: "noop", path };
}

/**
 * Remove Cursor rules for hack CLI usage.
 */
export async function removeCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  if (!(await pathExists(path))) {
    return { scope: opts.scope, status: "missing", path };
  }

  await unlink(path);
  return { scope: opts.scope, status: "removed", path };
}

/**
 * Render the Cursor rules template for hack CLI usage.
 */
export function renderCursorRules(): string {
  const lines = [
    "# hack CLI",
    "# Auto-generated by 'hack setup cursor' - do not remove these markers",
    MARKER_START,
    "",
    "This project uses `hack` for local runtime orchestration (compose + DNS/TLS + logs + sessions).",
    "Prefer `hack` when shell access is available. Use MCP only when shell access is unavailable.",
    "",
    "## Core Rules",
    "- Use `hack` CLI for start/stop/open/logs/run/session/tickets workflows.",
    "- Do not run raw `docker compose up/down/logs` for normal project operations.",
    "- Treat `.hack/.internal` and `.hack/.branch` as hack-managed artifacts; avoid manual edits there.",
    "- Use lifecycle/startup config in `.hack/hack.config.json` instead of ad-hoc host process tabs.",
    "- Use `--json` for machine-readable output when available.",
    "- If state is inconsistent, run `hack doctor` then `hack doctor --fix` before manual repairs.",
    "- For hostname routing, only services with Caddy labels on `hack-dev` are exposed (not every compose service).",
    "- Use `.hack.gy` alias hosts for OAuth-style callback validation when `.hack` is rejected by providers.",
    "",
    "## Managed Files",
    "- Source-of-truth: `.hack/docker-compose.yml`, `.hack/hack.config.json`, `.hack/hack.env.json`.",
    "- Generated/local-only: `.hack/.internal/compose.override.yml`, `.hack/.internal/compose.env.override.yml`, `.hack/.branch/compose.<branch>.override.yml`, `.hack/.internal/lifecycle/*`.",
    "- Manage dynamic host mappings with `hack internal extra-hosts ...` (not manual file edits).",
    "",
    "## Quick Reference",
    "```bash",
    "hack init",
    "hack up --detach",
    "hack up -d",
    "hack open --json",
    "hack open <sub>",
    "hack logs --pretty",
    "hack logs <service>",
    "hack logs --json --no-follow",
    "hack logs --loki --since 2h --pretty",
    "hack run <service> <cmd...>",
    "hack restart",
    "hack down",
    "hack global status",
    "hack session",
    "hack tickets list",
    "hack node list",
    "hack node status --watch",
    "hack node ssh setup --node <id>",
    "hack node routes status",
    "hack node routes repair",
    'hack dispatch run --project <name|id> --node default --branch <branch> --runner generic -- "pwd"',
    "hack internal extra-hosts list",
    "hack internal extra-hosts set <hostname> <target>",
    "hack internal extra-hosts unset <hostname>",
    "hack up --branch <name> --detach",
    "hack open --branch <name>",
    "hack logs --branch <name>",
    "hack down --branch <name>",
    "hack setup sync --all-scopes",
    "```",
    "",
    "## MCP (optional)",
    "- Install only for no-shell clients: `hack setup mcp`",
    "- Project-level hack commands auto-check integration drift and attempt auto-sync by default.",
    "- Use `HACK_SETUP_SYNC_MODE=warn` (warn only) or `HACK_SETUP_SYNC_MODE=off` (disable).",
    "- Refresh generated MCP/docs/instructions: `hack setup sync --all-scopes`",
    "",
    MARKER_END,
    "",
  ];

  return lines.join("\n");
}

function resolveCursorRulesPath(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}):
  | { readonly ok: true; readonly path: string }
  | { readonly ok: false; readonly message: string; readonly path?: string } {
  if (opts.scope === "project" && !opts.projectRoot) {
    return {
      ok: false,
      message: "Missing project root for project-scoped Cursor rules.",
    };
  }

  const root = opts.scope === "user" ? resolveHomeDir() : opts.projectRoot;
  if (!root) {
    return {
      ok: false,
      message: "HOME is not set; cannot resolve user rules path.",
    };
  }

  return { ok: true, path: resolve(root, RULES_DIR, RULES_FILENAME) };
}

function resolveHomeDir(): string | null {
  const home = (process.env.HOME ?? "").trim();
  return home.length > 0 ? home : null;
}

function resolveInstallStatus(opts: {
  readonly changed: boolean;
  readonly existed: boolean;
}): "created" | "updated" | "noop" {
  if (!opts.changed) {
    return "noop";
  }
  return opts.existed ? "updated" : "created";
}
