import { unlink } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  ensureDir,
  pathExists,
  readTextFile,
  writeTextFileIfChanged,
} from "../lib/fs.ts";
import {
  normalizeInstructionText,
  renderInstructionSections,
} from "./instruction-source.ts";

export type CursorScope = "project" | "user";

export type CursorRulesResult = {
  readonly scope: CursorScope;
  readonly status:
    | "created"
    | "updated"
    | "noop"
    | "stale"
    | "removed"
    | "missing"
    | "error";
  readonly path: string;
  readonly message?: string;
};

const RULES_FILENAME = "hack.mdc";
const RULES_DIR = ".cursor/rules";
const MARKER_START = "# BEGIN HACK INTEGRATION";
const MARKER_END = "# END HACK INTEGRATION";

/**
 * Install or update Cursor rules for hack CLI usage.
 */
export async function installCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  const existed = await pathExists(path);
  await ensureDir(dirname(path));
  const result = await writeTextFileIfChanged(path, renderCursorRules());

  const status = resolveInstallStatus({ changed: result.changed, existed });
  return { scope: opts.scope, status, path };
}

/**
 * Check whether Cursor rules are installed and current.
 *
 * Reports `stale` when the rules file exists but its content no longer
 * matches the current render (normalized comparison).
 */
export async function checkCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  const content = await readTextFile(path);
  if (!content) {
    return { scope: opts.scope, status: "missing", path };
  }

  if (!content.includes(MARKER_START)) {
    return {
      scope: opts.scope,
      status: "error",
      path,
      message: "Rules file exists but is missing hack integration markers.",
    };
  }

  const current = normalizeInstructionText({ text: renderCursorRules() });
  if (normalizeInstructionText({ text: content }) !== current) {
    return {
      scope: opts.scope,
      status: "stale",
      path,
      message: "Cursor rules content is out of date. Run: hack setup cursor",
    };
  }

  return { scope: opts.scope, status: "noop", path };
}

/**
 * Remove Cursor rules for hack CLI usage.
 */
export async function removeCursorRules(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}): Promise<CursorRulesResult> {
  const resolved = resolveCursorRulesPath(opts);
  if (!resolved.ok) {
    return {
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? RULES_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  if (!(await pathExists(path))) {
    return { scope: opts.scope, status: "missing", path };
  }

  await unlink(path);
  return { scope: opts.scope, status: "removed", path };
}

/**
 * Render the Cursor rules template for hack CLI usage.
 *
 * Marker framing lives here; the instructional content is the `rules`-tagged
 * sections from the shared instruction source.
 */
export function renderCursorRules(): string {
  const lines = [
    "# hack CLI",
    "# Auto-generated by 'hack setup cursor' - do not remove these markers",
    MARKER_START,
    "",
    "Hack v3 is local-first. This project uses `hack` for local runtime orchestration (compose + DNS/TLS + logs + sessions).",
    "Prefer `hack` when shell access is available. Use MCP only when shell access is unavailable.",
    "",
    renderInstructionSections({ surface: "rules", headingStyle: "markdown" }),
    "",
    MARKER_END,
    "",
  ];

  return lines.join("\n");
}

function resolveCursorRulesPath(opts: {
  readonly scope: CursorScope;
  readonly projectRoot?: string;
}):
  | { readonly ok: true; readonly path: string }
  | { readonly ok: false; readonly message: string; readonly path?: string } {
  if (opts.scope === "project" && !opts.projectRoot) {
    return {
      ok: false,
      message: "Missing project root for project-scoped Cursor rules.",
    };
  }

  const root = opts.scope === "user" ? resolveHomeDir() : opts.projectRoot;
  if (!root) {
    return {
      ok: false,
      message: "HOME is not set; cannot resolve user rules path.",
    };
  }

  return { ok: true, path: resolve(root, RULES_DIR, RULES_FILENAME) };
}

function resolveHomeDir(): string | null {
  const home = (process.env.HOME ?? "").trim();
  return home.length > 0 ? home : null;
}

function resolveInstallStatus(opts: {
  readonly changed: boolean;
  readonly existed: boolean;
}): "created" | "updated" | "noop" {
  if (!opts.changed) {
    return "noop";
  }
  return opts.existed ? "updated" : "created";
}
