import { rm } from "node:fs/promises";
import { dirname, resolve } from "node:path";

import {
  ensureDir,
  pathExists,
  readTextFile,
  writeTextFileIfChanged,
} from "../lib/fs.ts";
import { normalizeInstructionText } from "./instruction-source.ts";

/**
 * Agent-side `/hack-init` skill: a thin pointer that tells the agent to fetch
 * the canonical onboarding prompt from the CLI (`hack agent onboard`) or the
 * `hack-init` MCP prompt and follow it. The onboarding content itself lives in
 * `src/agents/onboarding-prompt.ts` — never in the installed skill file.
 *
 * Bundled in the native Hack plugins. The standalone Claude installer remains
 * only for recognizing and safely migrating artifacts from older releases.
 */

export type HackInitSkillClient = "claude";

export type HackInitSkillScope = "project" | "user";

export type HackInitSkillResult = {
  readonly client: HackInitSkillClient;
  readonly scope: HackInitSkillScope;
  readonly status:
    | "created"
    | "updated"
    | "noop"
    | "stale"
    | "removed"
    | "missing"
    | "error";
  readonly path: string;
  readonly message?: string;
};

const SKILL_NAME = "hack-init";
const SKILL_FILENAME = "SKILL.md";

const SKILL_DIRS: Readonly<Record<HackInitSkillClient, string>> = {
  claude: ".claude/skills",
};

const SETUP_COMMANDS: Readonly<Record<HackInitSkillClient, string>> = {
  claude: "hack setup claude",
};

/**
 * Render the `/hack-init` skill file. Kept intentionally thin: the skill only
 * routes the agent to the canonical prompt source.
 */
export function renderHackInitSkill(): string {
  return [
    "---",
    "name: hack-init",
    "description: >",
    "  Stand up or adopt hack in a project (agent-assisted onboarding).",
    "  Trigger when asked to set a repo up with hack, migrate a project onto",
    "  hack, or finish/repair a partial hack setup.",
    "---",
    "",
    "# hack init (agent-assisted onboarding)",
    "",
    "The full onboarding prompt is generated by the hack CLI — do not improvise the steps.",
    "",
    "1. Fetch the canonical onboarding prompt:",
    "   - With shell access: run `hack agent onboard` (works for new and existing projects).",
    "   - Without shell access: fetch the `hack-init` MCP prompt from the hack MCP server.",
    "2. Follow the printed prompt phase by phase (inventory, setup, platform nuances, running things, verification).",
    "3. Finish only when `hack doctor` is clean and every routable service responds.",
    "",
  ].join("\n");
}

/**
 * Install or update the `/hack-init` skill for a client at a scope.
 */
export async function installHackInitSkill(opts: {
  readonly client: HackInitSkillClient;
  readonly scope: HackInitSkillScope;
  readonly projectRoot?: string;
}): Promise<HackInitSkillResult> {
  const resolved = resolveHackInitSkillPath(opts);
  if (!resolved.ok) {
    return {
      client: opts.client,
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? SKILL_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  await ensureDir(dirname(path));
  const existed = await pathExists(path);
  const result = await writeTextFileIfChanged(path, renderHackInitSkill());

  const status = resolveInstallStatus({ changed: result.changed, existed });
  return { client: opts.client, scope: opts.scope, status, path };
}

/**
 * Check whether the `/hack-init` skill is installed and current for a client.
 *
 * Reports `stale` when the file exists but no longer matches the current
 * render (normalized comparison).
 */
export async function checkHackInitSkill(opts: {
  readonly client: HackInitSkillClient;
  readonly scope: HackInitSkillScope;
  readonly projectRoot?: string;
}): Promise<HackInitSkillResult> {
  const resolved = resolveHackInitSkillPath(opts);
  if (!resolved.ok) {
    return {
      client: opts.client,
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? SKILL_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  const content = await readTextFile(path);
  if (!content) {
    return { client: opts.client, scope: opts.scope, status: "missing", path };
  }

  const current = normalizeInstructionText({ text: renderHackInitSkill() });
  if (normalizeInstructionText({ text: content }) !== current) {
    return {
      client: opts.client,
      scope: opts.scope,
      status: "stale",
      path,
      message: `hack-init skill content is out of date. Run: ${SETUP_COMMANDS[opts.client]}`,
    };
  }

  return { client: opts.client, scope: opts.scope, status: "noop", path };
}

/**
 * Remove the `/hack-init` skill for a client at a scope.
 */
export async function removeHackInitSkill(opts: {
  readonly client: HackInitSkillClient;
  readonly scope: HackInitSkillScope;
  readonly projectRoot?: string;
}): Promise<HackInitSkillResult> {
  const resolved = resolveHackInitSkillPath(opts);
  if (!resolved.ok) {
    return {
      client: opts.client,
      scope: opts.scope,
      status: "error",
      path: resolved.path ?? SKILL_FILENAME,
      message: resolved.message,
    };
  }

  const path = resolved.path;
  if (!(await pathExists(path))) {
    return { client: opts.client, scope: opts.scope, status: "missing", path };
  }

  await rm(resolve(path, ".."), { recursive: true, force: true });
  return { client: opts.client, scope: opts.scope, status: "removed", path };
}

function resolveHackInitSkillPath(opts: {
  readonly client: HackInitSkillClient;
  readonly scope: HackInitSkillScope;
  readonly projectRoot?: string;
}):
  | { readonly ok: true; readonly path: string }
  | { readonly ok: false; readonly message: string; readonly path?: string } {
  if (opts.scope === "project" && !opts.projectRoot) {
    return {
      ok: false,
      message: "Missing project root for project-scoped hack-init skill.",
    };
  }

  const root = opts.scope === "user" ? resolveHomeDir() : opts.projectRoot;
  if (!root) {
    return {
      ok: false,
      message: "HOME is not set; cannot resolve hack-init skill path.",
    };
  }

  return {
    ok: true,
    path: resolve(root, SKILL_DIRS[opts.client], SKILL_NAME, SKILL_FILENAME),
  };
}

function resolveHomeDir(): string | null {
  const home = (process.env.HOME ?? "").trim();
  return home.length > 0 ? home : null;
}

function resolveInstallStatus(opts: {
  readonly changed: boolean;
  readonly existed: boolean;
}): "created" | "updated" | "noop" {
  if (!opts.changed) {
    return "noop";
  }
  return opts.existed ? "updated" : "created";
}
