/**
 * Render a concise patterns guide for agent-assisted init.
 */
export function renderAgentInitPatterns(): string {
  const lines = [
    "# hack agent init patterns",
    "",
    "Use these patterns to identify dependencies and ops steps during hack init.",
    "For the full agent-assisted onboarding flow, run `hack agent onboard`",
    "(or `hack init --with claude|codex|both` in a fresh repo); see",
    "docs/guides/agent-first-setup.md.",
    "",
    "Repo signals to scan:",
    "- docker-compose.yml / compose.yml (services + ports)",
    "- Dockerfile(s), Procfile, or task runners",
    "- package.json scripts (dev, start, db:migrate, seed)",
    "- Variable names in .env.example / .env.sample; never copy or print secret values",
    "- infra/, ops/, docker/, compose/ directories",
    "",
    "Common dependencies and hints:",
    "",
    "Postgres",
    "- services: postgres, db, pg",
    "- env: DATABASE_URL, PGHOST, PGUSER, PGPASSWORD, POSTGRES_*",
    "- files: prisma/schema.prisma, migrations/",
    "",
    "MySQL / MariaDB",
    "- services: mysql, mariadb",
    "- env: MYSQL_*, DATABASE_URL",
    "- files: prisma schema, migrations/",
    "",
    "Redis",
    "- services: redis",
    "- env: REDIS_URL, REDIS_HOST, REDIS_PORT",
    "",
    "MongoDB",
    "- services: mongo, mongodb",
    "- env: MONGO_URL, MONGODB_URI",
    "",
    "Queues / streaming",
    "- services: rabbitmq, nats, kafka, sqs",
    "- env: RABBITMQ_URL, NATS_URL, KAFKA_BROKERS, AWS_REGION",
    "",
    "Search",
    "- services: elasticsearch, opensearch, meilisearch",
    "- env: ELASTICSEARCH_URL, MEILI_HOST",
    "",
    "Auth / OAuth",
    "- env: AUTH_*, CLERK_*, SUPABASE_*, GOOGLE_*, GITHUB_*",
    "",
    "Storage",
    "- services: minio",
    "- env: S3_*, AWS_*, MINIO_*",
    "",
    "Mail",
    "- services: mailhog, mailpit",
    "- env: SMTP_*, RESEND_*, POSTMARK_*",
    "",
    "Ops checklist:",
    "- Include only processes chosen for containerization and their required dependencies; host app workflows remain valid.",
    "- Run migrations/seeds only when required and authorized for the selected development environment.",
    "- If host-side setup is required (auth proxy, tunnel, credential bootstrap), encode it in `.hack/hack.config.json` under `startup`/`lifecycle`.",
    "- For service-to-host proxy/tunnel routing, configure static `internal.extra_hosts` or dynamic mappings via `hack internal extra-hosts set`.",
    "- For routed local HTTP services, ensure services carry Caddy labels (`caddy`, `caddy.reverse_proxy`, `caddy.tls=internal`) and attach to `hack-dev`.",
    "- Use `.hack.gy` alias hosts for OAuth callback testing when provider rules reject `.hack`.",
    "- Treat `.hack/.internal/*` and `.hack/.branch/*` overrides as generated artifacts; keep edits in source config/compose files.",
    "- Use `hack run <service> <cmd...>` for one-off tasks.",
    "- Verify with `hack ps`, `hack open --json`, and finite `hack logs --no-follow --tail 100` reads.",
    "- When a persistent workspace is useful, use managed mux sessions (`hack session start <project> --new --name agent-1`).",
    "",
    "Patterns to consider:",
    "- Deps service: for containerized Node/Bun native dependencies, use the repo-pinned runtime and package manager with an isolated node_modules volume.",
    "- Ops service: reuse existing tooling; add a one-off service only when the container runtime or network is required.",
    "- If ports are not published, run container tooling through `hack run` or `hack exec`.",
    "",
    "Infer routine details from the repo; ask only when an unresolved answer blocks correctness:",
    "- What services are required for local dev?",
    "- Which command starts the app?",
    "- Any one-time setup steps (migrations, seeds, downloads)?",
    "",
  ];

  return lines.join("\n");
}
