/**
 * Render a concise patterns guide for agent-assisted init.
 */
export function renderAgentInitPatterns(): string {
  const lines = [
    "# hack agent init patterns",
    "",
    "Use these patterns to identify dependencies and ops steps during hack init.",
    "",
    "Repo signals to scan:",
    "- docker-compose.yml / compose.yml (services + ports)",
    "- Dockerfile(s), Procfile, or task runners",
    "- package.json scripts (dev, start, db:migrate, seed)",
    "- .env, .env.example, .env.sample",
    "- infra/, ops/, docker/, compose/ directories",
    "",
    "Common dependencies and hints:",
    "",
    "Postgres",
    "- services: postgres, db, pg",
    "- env: DATABASE_URL, PGHOST, PGUSER, PGPASSWORD, POSTGRES_*",
    "- files: prisma/schema.prisma, migrations/",
    "",
    "MySQL / MariaDB",
    "- services: mysql, mariadb",
    "- env: MYSQL_*, DATABASE_URL",
    "- files: prisma schema, migrations/",
    "",
    "Redis",
    "- services: redis",
    "- env: REDIS_URL, REDIS_HOST, REDIS_PORT",
    "",
    "MongoDB",
    "- services: mongo, mongodb",
    "- env: MONGO_URL, MONGODB_URI",
    "",
    "Queues / streaming",
    "- services: rabbitmq, nats, kafka, sqs",
    "- env: RABBITMQ_URL, NATS_URL, KAFKA_BROKERS, AWS_REGION",
    "",
    "Search",
    "- services: elasticsearch, opensearch, meilisearch",
    "- env: ELASTICSEARCH_URL, MEILI_HOST",
    "",
    "Auth / OAuth",
    "- env: AUTH_*, CLERK_*, SUPABASE_*, GOOGLE_*, GITHUB_*",
    "",
    "Storage",
    "- services: minio",
    "- env: S3_*, AWS_*, MINIO_*",
    "",
    "Mail",
    "- services: mailhog, mailpit",
    "- env: SMTP_*, RESEND_*, POSTMARK_*",
    "",
    "Ops checklist:",
    "- Ensure compose includes app + required deps (db/cache/queue).",
    "- Run migrations/seeds after services are up.",
    "- If host-side setup is required (auth proxy, tunnel, credential bootstrap), encode it in `.hack/hack.config.json` under `startup`/`lifecycle`.",
    "- For service-to-host proxy/tunnel routing, configure static `internal.extra_hosts` or dynamic mappings via `hack internal extra-hosts set`.",
    "- For externally reachable local HTTP routes, ensure services carry Caddy labels (`caddy`, `caddy.reverse_proxy`, `caddy.tls=internal`) and attach to `hack-dev`.",
    "- Use `.hack.gy` alias hosts for OAuth callback testing when provider rules reject `.hack`.",
    "- Treat `.hack/.internal/*` and `.hack/.branch/*` overrides as generated artifacts; keep edits in source config/compose files.",
    "- Use `hack run <service> <cmd...>` for one-off tasks.",
    "- Verify with `hack ps`, `hack open --json`, `hack logs --pretty`.",
    "- For long-lived agent work, run in managed mux sessions (`hack session start <project> --new --name agent-1`).",
    "- Track follow-up work in git-backed tickets (`hack tickets ...`).",
    "",
    "Patterns to consider:",
    "- Deps service: run `bun install` inside a container and share node_modules via a volume.",
    "- Ops service: add a one-off service for migrations/seeds inside the compose network.",
    "- If ports are not published, always run ops via `hack run` or `docker compose exec`.",
    "",
    "If signals are missing, ask the user:",
    "- What services are required for local dev?",
    "- Which command starts the app?",
    "- Any one-time setup steps (migrations, seeds, downloads)?",
    "",
  ];

  return lines.join("\n");
}
