/**
 * Render a concise CLI-first primer for coding agents.
 */
export function renderAgentPrimer(): string {
  const lines = [
    "# hack CLI primer",
    "",
    "Use `hack` CLI for local dev when shell access is available. Prefer CLI over MCP.",
    "",
    "Rules:",
    "- Prefer `hack` over raw `docker` / `docker compose` for runtime operations.",
    "- Keep startup/lifecycle behavior in `.hack/hack.config.json`.",
    "- Use `hack doctor` and `hack doctor --fix` before manual runtime/network repair.",
    "",
    "Quick start:",
    "- Initialize config (if missing): `hack init`",
    "- Start services: `hack up --detach`",
    "- Alternate shorthand: `hack up -d`",
    "- Open app: `hack open --json`",
    "- Tail logs: `hack logs --pretty`",
    "- Per-service logs: `hack logs <service>`",
    "- Snapshot logs: `hack logs --json --no-follow`",
    "- Loki history: `hack logs --loki --since 2h --pretty`",
    "- Run command: `hack run <service> <cmd...>`",
    "- Restart: `hack restart`",
    "- Stop services: `hack down`",
    "",
    "Config:",
    "- Project: `.hack/hack.config.json`",
    "- Global: `~/.hack/hack.config.json`",
    "- Schema: `https://schemas.hack/hack.config.schema.json`",
    "",
    "Global + workflows:",
    "- Global infra status: `hack global status`",
    "- Sessions: `hack session`",
    "- Tickets: `hack tickets list`",
    "",
    "Branch instances (parallel envs):",
    "- `hack up --branch <name> --detach`",
    "- `hack open --branch <name>`",
    "- `hack logs --branch <name>`",
    "- `hack down --branch <name>`",
    "",
    "Logs:",
    "- Loki history: `hack logs --loki --since 2h --pretty`",
    "- Force compose: `hack logs --compose`",
    "",
    "Project targeting:",
    "- Run from repo root, or use `--project <name>` / `--path <repo-root>`.",
    "",
    "Init assistance:",
    "- Generate init prompt: `hack agent init`",
    "- Patterns checklist: `hack agent patterns`",
    "",
    "Agent integration maintenance:",
    "- Refresh project + global integrations: `hack setup sync --all-scopes`",
    "- Audit only: `hack setup sync --all-scopes --check`",
    "- Remove generated integrations: `hack setup sync --all-scopes --remove`",
    "",
    "MCP:",
    "- Use MCP only when no shell access. Install via `hack setup mcp`.",
    "",
  ];

  return lines.join("\n");
}
