/**
 * Render a concise CLI-first primer for coding agents.
 */
export function renderAgentPrimer(): string {
  const lines = [
    "# hack CLI primer",
    "",
    "Use `hack` CLI for local-first dev when shell access is available. Prefer CLI over MCP.",
    "",
    "Supported v3 surface:",
    "- Core: `hack init`, `up/down/restart`, `open`, `logs`, `env`, `host exec/shell`, `session`, `doctor`, `daemon`.",
    "- Optional: local git-backed `hack tickets`.",
    "- Removed: hosted auth/account/org/team flows, web dashboard, built-in GitHub workflows, and built-in Linear sync.",
    "- Unsupported experimental: remote/gateway/node/dispatch. Do not use these unless explicitly requested.",
    "",
    "Rules:",
    "- Prefer `hack` over raw `docker` / `docker compose` for runtime operations.",
    "- Keep startup/lifecycle behavior in `.hack/hack.config.json`.",
    "- Treat `.hack/.internal` and `.hack/.branch` as hack-managed artifacts; avoid manual edits there.",
    "- Use `hack doctor` and `hack doctor --fix` before manual runtime/network repair.",
    "",
    "Quick start:",
    "- Initialize config (if missing): `hack init`",
    "- Start services: `hack up --detach`",
    "- Alternate shorthand: `hack up -d`",
    "- Open app: `hack open --json`",
    "- Tail logs: `hack logs --pretty`",
    "- Per-service logs: `hack logs <service>`",
    "- Snapshot logs: `hack logs --json --no-follow`",
    "- Loki history: `hack logs --loki --since 2h --pretty`",
    "- Run command: `hack run <service> <cmd...>`",
    "- Restart: `hack restart`",
    "- Stop services: `hack down`",
    "",
    "Config:",
    "- Project: `.hack/hack.config.json`",
    "- Global: `~/.hack/hack.config.json`",
    "- Schema: `https://schemas.hack/hack.config.schema.json`",
    "",
    "Hostnames + routing:",
    "- `dev_host` is the base host (default: `<project>.hack`).",
    "- Routed subdomains use `<sub>.<dev_host>` (for example `api.myapp.hack`).",
    "- OAuth alias adds `<dev_host>.<tld>` / `<sub>.<dev_host>.<tld>` (default tld: `gy`).",
    "- Only Caddy-labeled HTTP services on `hack-dev` are reachable via these hostnames.",
    "",
    "TLS + provider constraints:",
    "- Routed hostnames use Caddy internal PKI (trust CA via `hack global trust`).",
    "- `.hack` works locally but is not a public suffix.",
    "- Use alias hosts like `*.hack.gy` when provider callback validation rejects `.hack`.",
    "",
    "Managed files:",
    "- Source-of-truth: `.hack/docker-compose.yml`, `.hack/hack.config.json`, `.hack/hack.env.default.yaml`, optional `.hack/hack.env.<overlay>.yaml`.",
    "- Worktree-local env overrides: `.hack/hack.env.local.yaml`, `.hack/hack.env.<overlay>.local.yaml`.",
    "- Generated/local-only: `.hack.secret.key`, `.hack/.env`, `.hack/.env.state.json`, `.hack/.internal/compose.override.yml`, `.hack/.internal/compose.env.override.yml`, `.hack/.branch/compose.<branch>.override.yml`, `.hack/.internal/lifecycle/*`.",
    "- Dynamic host mappings: `hack internal extra-hosts set|unset|list` (writes `.hack/.internal/extra-hosts.json`).",
    "",
    "Proxies/tunnels:",
    "- Static mappings: set `internal.extra_hosts` in `.hack/hack.config.json`.",
    "- For local proxies, prefer `host-gateway` targets when possible.",
    "- After changes/IP churn: `hack restart` then `hack doctor`.",
    "",
    "Global + workflows:",
    "- Global infra status: `hack global status`",
    "- Sessions: `hack session`",
    "- Tickets: `hack tickets list`",
    "",
    "Lifecycle:",
    "- Put host setup in `.hack/hack.config.json` under `startup` / `lifecycle`.",
    "- Use lifecycle processes for long-running host tasks instead of ad-hoc terminal tabs.",
    '- For fixed-port helpers such as SSM tunnels or local proxies, use `singleton.ports` with `onConflict: "adopt"` when an already-running equivalent helper should be reused.',
    "- Adoption means Hack skips starting another copy and leaves the external listener alone on `hack down`.",
    "",
    "Host env helpers:",
    "- Host command: `hack host exec --env qa --scope api -- bun db:migrate`",
    "- Host shell: `hack host shell --env qa --scope api`",
    "- Use `--target compose` only when a host command needs container-oriented addresses.",
    "",
    "Unsupported experimental remote ops:",
    "- Pair/register nodes: `hack node pair ...`, `hack node list`, `hack node status --watch`.",
    "- Repair SSH for remote Git/mutagen: `hack node ssh setup --node <id>`.",
    "- Inspect node workspace map on remote host: `ssh <user@host> 'hack node workspace list --json'`.",
    "- Inspect/repair controller route bridge: `hack node routes status`, `hack node routes repair`.",
    '- Dispatch remote command: `hack dispatch run --project <name|id> --node default --branch <branch> --runner generic -- "pwd"`.',
    "",
    "Branch instances (parallel envs):",
    "- `hack up --branch <name> --detach`",
    "- `hack open --branch <name>`",
    "- `hack logs --branch <name>`",
    "- `hack down --branch <name>`",
    "",
    "Logs:",
    "- Loki history: `hack logs --loki --since 2h --pretty`",
    "- Force compose: `hack logs --compose`",
    "",
    "Project targeting:",
    "- Run from repo root, or use `--project <name>` / `--path <repo-root>`.",
    "",
    "Init assistance:",
    "- Generate init prompt: `hack agent init`",
    "- Patterns checklist: `hack agent patterns`",
    "",
    "Agent integration maintenance:",
    "- Project-level hack commands auto-check drift and attempt auto-sync for docs/skills/MCP.",
    "- Set `HACK_SETUP_SYNC_MODE=warn` to warn-only, or `HACK_SETUP_SYNC_MODE=off` to disable.",
    "- Refresh project + global integrations: `hack setup sync --all-scopes`",
    "- Audit only: `hack setup sync --all-scopes --check`",
    "- Remove generated integrations: `hack setup sync --all-scopes --remove`",
    "",
    "MCP:",
    "- Use MCP only when no shell access. Install via `hack setup mcp`.",
    "",
  ];

  return lines.join("\n");
}
