/**
 * Render portable guidance for preparing an existing Hack project on another
 * machine. Runtime selection stays explicit; this skill does not provision a
 * cloud host or turn a portable CLI install into native-runtime acceptance.
 */
export function renderHackRemoteSkill(): string {
  return [
    "---",
    "name: hack-remote",
    "description: >",
    "  Prepare and verify an existing Hack project on a fresh remote development",
    "  machine, in Codex Cloud, or in a managed CI container. Use for installing",
    "  the selected Hack CLI, supplying an env key securely, installing locked",
    "  dependencies, and starting the project's supported development workflow.",
    "---",
    "",
    "# Prepare a Hack project remotely",
    "",
    "Start with the existing repository and the requested development workflow. Reuse its Hack configuration, runtime pins, lockfiles, and documented start commands. Installing this plugin does not install Hack, provide credentials, provision a machine, or make a local MCP connection available in a cloud task.",
    "",
    "## Identify the target and selected CLI",
    "",
    "1. Establish the authorized machine or cloud environment, checkout, intended branch, non-production env overlay, and success check. Infer these from the request and repository when possible. Ask only for missing information that blocks correct execution. Creating cloud resources, publishing/sharing a cloud environment, changing production, and privileged host setup need authority for that effect.",
    "2. Read AGENTS.md and the project's setup instructions. Inspect non-secret Hack configuration and runtime pins; never dump env files, process environments, key files, or secret values. Check `uname -s`, `uname -m`, `git status --short`, and `git rev-parse --show-toplevel` on the target itself.",
    "3. Select an absolute CLI path and check its `--version` and `--help`. For an installed native candidate, select that channel's `bin/hack-next` launcher. A bare candidate `hack-cli` does not select its native executor or private homes. Keep stable and candidate state separate; never silently fall back to whichever `hack` appears on PATH.",
    "",
    "Use `hack_cli` and `project_root` below as local shell variables containing those reviewed absolute paths; they are not Hack configuration keys. Set `HACK_NO_INTERACTIVE=1` and `NO_COLOR=1` for unattended commands. An interactive requirement must fail visibly rather than wait forever.",
    "",
    "## Install only what this target can run",
    "",
    "- If the selected CLI is absent, use a specific approved release tag and the matching platform artifact. The portable `hack-codex-install.sh` accepts `HACK_INSTALL_TAG`, `HACK_INSTALL_BIN`, and `HACK_INSTALL_ASSETS`. Download the script from that exact GitHub release, inspect it, then install into dedicated paths. Do not use `latest`, overwrite a different channel, or treat the slim installer as the native prerelease installer.",
    "- Portable/slim mode (`HACK_EXECUTION_MODE=codex`) supports env resolution and `host exec`; it skips machine-wide routing, TLS, observability services, and Docker event watching. It does not install Docker, a VM provider, or project dependencies. The current native prerelease installer supports Apple Silicon macOS; native Linux/cloud provisioning remains unqualified.",
    "- For an existing Compose workflow, verify `docker info` and `docker compose version` on the authorized target before starting services. A Docker client alone is insufficient. Use Hack to manage project services. If the engine is missing, report the requirement or perform an explicitly authorized host setup; do not switch to unsupported Hack node/gateway/dispatch commands or assume nested virtualization is available.",
    "- Install the repository's pinned toolchain and use its locked dependency command, such as `bun install --frozen-lockfile` for a Bun project. A lockfile failure requires diagnosis; do not retry with an unlocked install. Use an existing host development script when it is the project's supported portable path.",
    "",
    "## Supply the env key without exposing it",
    "",
    "Request `HACK_ENV_SECRET_KEY` through the target's approved secret manager or direct process injection. The user enters the value in its native secret UI, never in chat. Hack needs the real key bytes locally to decrypt the committed env; an HTTPS proxy placeholder cannot replace them. Do not print the key, pass it as a command argument, write it into a plugin, image, shell profile, or cached file, or export decrypted values for later reuse. Use non-production credentials and review the chosen command's own logging.",
    "",
    "Current Codex Cloud uses an Install script and Start skill. Request the key as a direct environment variable, preferably a personal value scoped to the chosen environment; it is available to the task. Network secrets substitute HTTPS credentials and cannot decrypt Hack env. Keep prepared files free of keys and plaintext secrets. After approved publication, verify a fresh task. See [current Cloud environments](https://learn.chatgpt.com/docs/environments/cloud-environments).",
    "",
    "Legacy Codex Cloud secrets are setup-only and removed before the agent phase; a setup export does not persist. Do not bypass that boundary by saving the key or decrypted env in cached files. Runtime decryption needs a separately authorized injection mechanism, or the task must use a secret-free workflow. See [legacy Cloud environments](https://learn.chatgpt.com/docs/environments/cloud-environment).",
    "",
    "Cloud tasks must have this skill in their repository or supported cloud environment; a personal plugin installed on a local computer is not proof it is loaded remotely. Confirm the available skills in the target task.",
    "",
    "## Start and verify the requested workflow",
    "",
    "Use the selected CLI for every command. From the intended checkout, inspect resolution without exposing values:",
    "",
    "```sh",
    '"$hack_cli" env explain DATABASE_URL --path "$project_root" --env default --json',
    '"$hack_cli" host exec --path "$project_root" --env default -- sh -c \'test -n "$DATABASE_URL"\'',
    "```",
    "",
    "Replace DATABASE_URL with a declared required key name and `default` with the authorized overlay; add `--scope SERVICE` to `host exec` for service-scoped values. The boolean check proves injection, not service connectivity. Run the repository's actual test/start command through `host exec` when it uses host dependencies. `--target compose` changes the env view; it does not start a container.",
    "",
    "When the selected runtime is ready and the project's lifecycle hooks have been reviewed for this target:",
    "",
    "```sh",
    '"$hack_cli" up --detach --path "$project_root" --env default --json',
    '"$hack_cli" ps --path "$project_root" --json',
    "```",
    "",
    "Check an actual application endpoint or repository health command with a bounded timeout, then perform one meaningful development operation. Follow the project's approved network access and authentication flow; do not bypass provider restrictions. Report the CLI version/path, target, workflow, env overlay name, readiness result, and remaining blocker without secrets. Installation, a listed MCP server, or a running container alone does not prove the app works. Stop only resources created and owned by this task when cleanup is requested; preserve reusable caches and application data.",
    "",
  ].join("\n");
}
